FROM gcr.io/google_appengine/openjdk8
COPY target/spring-boot-sample-web-ui-1.4.0.BUILD-SNAPSHOT.jar target/spring-boot-sample-web-ui-1.4.0.BUILD-SNAPSHOT.jar
CMD ["java", "-jar", "target/spring-boot-sample-web-ui-1.4.0.BUILD-SNAPSHOT.jar"]
